"""initial_schema

Revision ID: ba6c33b46bf1
Revises: 
Create Date: 2026-06-28 17:46:56.926340

"""
import sys
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

src = Path(__file__).resolve().parents[2] / "src"
if str(src) not in sys.path:
    sys.path.insert(0, str(src))

from rabeeh_core.persistence.models import GUID

# revision identifiers, used by Alembic.
revision: str = 'ba6c33b46bf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_boqs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=512), nullable=False),
    sa.Column('boq_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boq_number')
    )
    op.create_index(op.f('ix_business_boqs_status'), 'business_boqs', ['status'], unique=False)
    op.create_table('business_customers',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_customers_name'), 'business_customers', ['name'], unique=False)
    op.create_table('business_estimations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=512), nullable=False),
    sa.Column('estimation_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_materials_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_overhead', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimation_number')
    )
    op.create_index(op.f('ix_business_estimations_status'), 'business_estimations', ['status'], unique=False)
    op.create_table('business_vendors',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('contact_person', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_vendors_name'), 'business_vendors', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('session_id', GUID(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('tool_results', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_session_id'), 'tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('business_boq_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('boq_id', GUID(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['business_boqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_boq_items_boq_id'), 'business_boq_items', ['boq_id'], unique=False)
    op.create_table('business_estimation_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('estimation_id', GUID(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('material_cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['estimation_id'], ['business_estimations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_estimation_items_estimation_id'), 'business_estimation_items', ['estimation_id'], unique=False)
    op.create_table('business_inventory',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor_id', GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['business_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_index(op.f('ix_business_inventory_category'), 'business_inventory', ['category'], unique=False)
    op.create_table('business_invoices',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('customer_id', GUID(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['business_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_business_invoices_customer_id'), 'business_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_business_invoices_status'), 'business_invoices', ['status'], unique=False)
    op.create_table('business_purchase_orders',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('vendor_id', GUID(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['business_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_business_purchase_orders_status'), 'business_purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_business_purchase_orders_vendor_id'), 'business_purchase_orders', ['vendor_id'], unique=False)
    op.create_table('business_quotations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('customer_id', GUID(length=36), nullable=False),
    sa.Column('quote_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['business_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index(op.f('ix_business_quotations_customer_id'), 'business_quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_business_quotations_status'), 'business_quotations', ['status'], unique=False)
    op.create_table('task_events',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task_id', GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index('ix_task_events_task_kind', 'task_events', ['task_id', 'kind'], unique=False)
    op.create_table('business_invoice_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('invoice_id', GUID(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['business_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_invoice_items_invoice_id'), 'business_invoice_items', ['invoice_id'], unique=False)
    op.create_table('business_po_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('po_id', GUID(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['business_purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_po_items_po_id'), 'business_po_items', ['po_id'], unique=False)
    op.create_table('business_quotation_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('quotation_id', GUID(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['business_quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_quotation_items_quotation_id'), 'business_quotation_items', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_quotation_items_quotation_id'), table_name='business_quotation_items')
    op.drop_table('business_quotation_items')
    op.drop_index(op.f('ix_business_po_items_po_id'), table_name='business_po_items')
    op.drop_table('business_po_items')
    op.drop_index(op.f('ix_business_invoice_items_invoice_id'), table_name='business_invoice_items')
    op.drop_table('business_invoice_items')
    op.drop_index('ix_task_events_task_kind', table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_business_quotations_status'), table_name='business_quotations')
    op.drop_index(op.f('ix_business_quotations_customer_id'), table_name='business_quotations')
    op.drop_table('business_quotations')
    op.drop_index(op.f('ix_business_purchase_orders_vendor_id'), table_name='business_purchase_orders')
    op.drop_index(op.f('ix_business_purchase_orders_status'), table_name='business_purchase_orders')
    op.drop_table('business_purchase_orders')
    op.drop_index(op.f('ix_business_invoices_status'), table_name='business_invoices')
    op.drop_index(op.f('ix_business_invoices_customer_id'), table_name='business_invoices')
    op.drop_table('business_invoices')
    op.drop_index(op.f('ix_business_inventory_category'), table_name='business_inventory')
    op.drop_table('business_inventory')
    op.drop_index(op.f('ix_business_estimation_items_estimation_id'), table_name='business_estimation_items')
    op.drop_table('business_estimation_items')
    op.drop_index(op.f('ix_business_boq_items_boq_id'), table_name='business_boq_items')
    op.drop_table('business_boq_items')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_session_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_business_vendors_name'), table_name='business_vendors')
    op.drop_table('business_vendors')
    op.drop_index(op.f('ix_business_estimations_status'), table_name='business_estimations')
    op.drop_table('business_estimations')
    op.drop_index(op.f('ix_business_customers_name'), table_name='business_customers')
    op.drop_table('business_customers')
    op.drop_index(op.f('ix_business_boqs_status'), table_name='business_boqs')
    op.drop_table('business_boqs')
    # ### end Alembic commands ###
